//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 216.151697 on Stable branch
// Generated with ALiVE version 2.1.2.2309211
//////////////////////////////////////////////////////////////////////////////////

class CfgFactionClasses {
    class CIV_F_Cher90 {
        displayName = "Civilians (Chernarus 90s)";
        side = 3;
        flag = "\ca\data\flag_chernarus_co.paa";
        icon = "\ca\data\flag_chernarus_co.paa";
        priority = 0;
    };
};

class CfgGroups {
    class Civilian {

        class CIV_F_Cher90 {
            name = "Civilians (Chernarus 90s)";

            class Infantry {
                name = "Infantry";

            };

            class SpecOps {
                name = "Special Forces";

            };

            class Motorized {
                name = "Motorized Infantry";

            };

            class Motorized_MTP {
                name = "Motorized Infantry (MTP)";

            };

            class Support {
                name = "Support Infantry";

            };

            class Mechanized {
                name = "Mechanized Infantry";

            };

            class Armored {
                name = "Armor";

            };

            class Artillery {
                name = "Artillery";

            };

            class Naval {
                name = "Naval";

            };

            class Air {
                name = "Air";

            };


        };

    };
};


class CBA_Extended_EventHandlers_base;

class CfgVehicles {

    class LOP_CHR_Civ_Villager_01;
    class LOP_CHR_Civ_Villager_01_OCimport_01 : LOP_CHR_Civ_Villager_01 { scope = 0; class EventHandlers; };
    class LOP_CHR_Civ_Villager_01_OCimport_02 : LOP_CHR_Civ_Villager_01_OCimport_01 { class EventHandlers; };

    class LOP_CHR_Civ_Villager_02;
    class LOP_CHR_Civ_Villager_02_OCimport_01 : LOP_CHR_Civ_Villager_02 { scope = 0; class EventHandlers; };
    class LOP_CHR_Civ_Villager_02_OCimport_02 : LOP_CHR_Civ_Villager_02_OCimport_01 { class EventHandlers; };

    class LOP_CHR_Civ_Villager_03;
    class LOP_CHR_Civ_Villager_03_OCimport_01 : LOP_CHR_Civ_Villager_03 { scope = 0; class EventHandlers; };
    class LOP_CHR_Civ_Villager_03_OCimport_02 : LOP_CHR_Civ_Villager_03_OCimport_01 { class EventHandlers; };

    class LOP_CHR_Civ_Villager_04;
    class LOP_CHR_Civ_Villager_04_OCimport_01 : LOP_CHR_Civ_Villager_04 { scope = 0; class EventHandlers; };
    class LOP_CHR_Civ_Villager_04_OCimport_02 : LOP_CHR_Civ_Villager_04_OCimport_01 { class EventHandlers; };

    class LOP_CHR_Civ_Woodlander_01;
    class LOP_CHR_Civ_Woodlander_01_OCimport_01 : LOP_CHR_Civ_Woodlander_01 { scope = 0; class EventHandlers; };
    class LOP_CHR_Civ_Woodlander_01_OCimport_02 : LOP_CHR_Civ_Woodlander_01_OCimport_01 { class EventHandlers; };

    class LOP_CHR_Civ_Woodlander_02;
    class LOP_CHR_Civ_Woodlander_02_OCimport_01 : LOP_CHR_Civ_Woodlander_02 { scope = 0; class EventHandlers; };
    class LOP_CHR_Civ_Woodlander_02_OCimport_02 : LOP_CHR_Civ_Woodlander_02_OCimport_01 { class EventHandlers; };

    class LOP_CHR_Civ_Woodlander_03;
    class LOP_CHR_Civ_Woodlander_03_OCimport_01 : LOP_CHR_Civ_Woodlander_03 { scope = 0; class EventHandlers; };
    class LOP_CHR_Civ_Woodlander_03_OCimport_02 : LOP_CHR_Civ_Woodlander_03_OCimport_01 { class EventHandlers; };

    class LOP_CHR_Civ_Woodlander_04;
    class LOP_CHR_Civ_Woodlander_04_OCimport_01 : LOP_CHR_Civ_Woodlander_04 { scope = 0; class EventHandlers; };
    class LOP_CHR_Civ_Woodlander_04_OCimport_02 : LOP_CHR_Civ_Woodlander_04_OCimport_01 { class EventHandlers; };

    class LOP_CHR_Civ_Worker_01;
    class LOP_CHR_Civ_Worker_01_OCimport_01 : LOP_CHR_Civ_Worker_01 { scope = 0; class EventHandlers; };
    class LOP_CHR_Civ_Worker_01_OCimport_02 : LOP_CHR_Civ_Worker_01_OCimport_01 { class EventHandlers; };

    class LOP_CHR_Civ_Worker_02;
    class LOP_CHR_Civ_Worker_02_OCimport_01 : LOP_CHR_Civ_Worker_02 { scope = 0; class EventHandlers; };
    class LOP_CHR_Civ_Worker_02_OCimport_02 : LOP_CHR_Civ_Worker_02_OCimport_01 { class EventHandlers; };

    class LOP_CHR_Civ_Worker_03;
    class LOP_CHR_Civ_Worker_03_OCimport_01 : LOP_CHR_Civ_Worker_03 { scope = 0; class EventHandlers; };
    class LOP_CHR_Civ_Worker_03_OCimport_02 : LOP_CHR_Civ_Worker_03_OCimport_01 { class EventHandlers; };

    class LOP_CHR_Civ_Worker_04;
    class LOP_CHR_Civ_Worker_04_OCimport_01 : LOP_CHR_Civ_Worker_04 { scope = 0; class EventHandlers; };
    class LOP_CHR_Civ_Worker_04_OCimport_02 : LOP_CHR_Civ_Worker_04_OCimport_01 { class EventHandlers; };

    class LOP_CHR_Civ_Rocker_01;
    class LOP_CHR_Civ_Rocker_01_OCimport_01 : LOP_CHR_Civ_Rocker_01 { scope = 0; class EventHandlers; };
    class LOP_CHR_Civ_Rocker_01_OCimport_02 : LOP_CHR_Civ_Rocker_01_OCimport_01 { class EventHandlers; };

    class LOP_CHR_Civ_Rocker_02;
    class LOP_CHR_Civ_Rocker_02_OCimport_01 : LOP_CHR_Civ_Rocker_02 { scope = 0; class EventHandlers; };
    class LOP_CHR_Civ_Rocker_02_OCimport_02 : LOP_CHR_Civ_Rocker_02_OCimport_01 { class EventHandlers; };

    class LOP_CHR_Civ_Rocker_03;
    class LOP_CHR_Civ_Rocker_03_OCimport_01 : LOP_CHR_Civ_Rocker_03 { scope = 0; class EventHandlers; };
    class LOP_CHR_Civ_Rocker_03_OCimport_02 : LOP_CHR_Civ_Rocker_03_OCimport_01 { class EventHandlers; };

    class LOP_CHR_Civ_Rocker_04;
    class LOP_CHR_Civ_Rocker_04_OCimport_01 : LOP_CHR_Civ_Rocker_04 { scope = 0; class EventHandlers; };
    class LOP_CHR_Civ_Rocker_04_OCimport_02 : LOP_CHR_Civ_Rocker_04_OCimport_01 { class EventHandlers; };

    class LOP_CHR_Civ_Profiteer_01;
    class LOP_CHR_Civ_Profiteer_01_OCimport_01 : LOP_CHR_Civ_Profiteer_01 { scope = 0; class EventHandlers; };
    class LOP_CHR_Civ_Profiteer_01_OCimport_02 : LOP_CHR_Civ_Profiteer_01_OCimport_01 { class EventHandlers; };

    class LOP_CHR_Civ_Profiteer_02;
    class LOP_CHR_Civ_Profiteer_02_OCimport_01 : LOP_CHR_Civ_Profiteer_02 { scope = 0; class EventHandlers; };
    class LOP_CHR_Civ_Profiteer_02_OCimport_02 : LOP_CHR_Civ_Profiteer_02_OCimport_01 { class EventHandlers; };

    class LOP_CHR_Civ_Profiteer_03;
    class LOP_CHR_Civ_Profiteer_03_OCimport_01 : LOP_CHR_Civ_Profiteer_03 { scope = 0; class EventHandlers; };
    class LOP_CHR_Civ_Profiteer_03_OCimport_02 : LOP_CHR_Civ_Profiteer_03_OCimport_01 { class EventHandlers; };

    class LOP_CHR_Civ_Profiteer_04;
    class LOP_CHR_Civ_Profiteer_04_OCimport_01 : LOP_CHR_Civ_Profiteer_04 { scope = 0; class EventHandlers; };
    class LOP_CHR_Civ_Profiteer_04_OCimport_02 : LOP_CHR_Civ_Profiteer_04_OCimport_01 { class EventHandlers; };

    class LOP_CHR_Civ_Priest_01;
    class LOP_CHR_Civ_Priest_01_OCimport_01 : LOP_CHR_Civ_Priest_01 { scope = 0; class EventHandlers; };
    class LOP_CHR_Civ_Priest_01_OCimport_02 : LOP_CHR_Civ_Priest_01_OCimport_01 { class EventHandlers; };

    class LOP_CHR_Civ_Doctor_01;
    class LOP_CHR_Civ_Doctor_01_OCimport_01 : LOP_CHR_Civ_Doctor_01 { scope = 0; class EventHandlers; };
    class LOP_CHR_Civ_Doctor_01_OCimport_02 : LOP_CHR_Civ_Doctor_01_OCimport_01 { class EventHandlers; };

    class LOP_CHR_Civ_SchoolTeacher;
    class LOP_CHR_Civ_SchoolTeacher_OCimport_01 : LOP_CHR_Civ_SchoolTeacher { scope = 0; class EventHandlers; };
    class LOP_CHR_Civ_SchoolTeacher_OCimport_02 : LOP_CHR_Civ_SchoolTeacher_OCimport_01 { class EventHandlers; };

    class LOP_CHR_Civ_Assistant;
    class LOP_CHR_Civ_Assistant_OCimport_01 : LOP_CHR_Civ_Assistant { scope = 0; class EventHandlers; };
    class LOP_CHR_Civ_Assistant_OCimport_02 : LOP_CHR_Civ_Assistant_OCimport_01 { class EventHandlers; };

    class LOP_CHR_Civ_Policeman_01;
    class LOP_CHR_Civ_Policeman_01_OCimport_01 : LOP_CHR_Civ_Policeman_01 { scope = 0; class EventHandlers; };
    class LOP_CHR_Civ_Policeman_01_OCimport_02 : LOP_CHR_Civ_Policeman_01_OCimport_01 { class EventHandlers; };

    class LOP_CHR_Civ_Functionary_01;
    class LOP_CHR_Civ_Functionary_01_OCimport_01 : LOP_CHR_Civ_Functionary_01 { scope = 0; class EventHandlers; };
    class LOP_CHR_Civ_Functionary_01_OCimport_02 : LOP_CHR_Civ_Functionary_01_OCimport_01 { class EventHandlers; };

    class LOP_CHR_Civ_Functionary_02;
    class LOP_CHR_Civ_Functionary_02_OCimport_01 : LOP_CHR_Civ_Functionary_02 { scope = 0; class EventHandlers; };
    class LOP_CHR_Civ_Functionary_02_OCimport_02 : LOP_CHR_Civ_Functionary_02_OCimport_01 { class EventHandlers; };

    class LOP_CHR_Civ_Citizen_01;
    class LOP_CHR_Civ_Citizen_01_OCimport_01 : LOP_CHR_Civ_Citizen_01 { scope = 0; class EventHandlers; };
    class LOP_CHR_Civ_Citizen_01_OCimport_02 : LOP_CHR_Civ_Citizen_01_OCimport_01 { class EventHandlers; };

    class LOP_CHR_Civ_Citizen_02;
    class LOP_CHR_Civ_Citizen_02_OCimport_01 : LOP_CHR_Civ_Citizen_02 { scope = 0; class EventHandlers; };
    class LOP_CHR_Civ_Citizen_02_OCimport_02 : LOP_CHR_Civ_Citizen_02_OCimport_01 { class EventHandlers; };

    class LOP_CHR_Civ_Citizen_03;
    class LOP_CHR_Civ_Citizen_03_OCimport_01 : LOP_CHR_Civ_Citizen_03 { scope = 0; class EventHandlers; };
    class LOP_CHR_Civ_Citizen_03_OCimport_02 : LOP_CHR_Civ_Citizen_03_OCimport_01 { class EventHandlers; };

    class LOP_CHR_Civ_Citizen_04;
    class LOP_CHR_Civ_Citizen_04_OCimport_01 : LOP_CHR_Civ_Citizen_04 { scope = 0; class EventHandlers; };
    class LOP_CHR_Civ_Citizen_04_OCimport_02 : LOP_CHR_Civ_Citizen_04_OCimport_01 { class EventHandlers; };

    class LOP_CHR_Civ_Random;
    class LOP_CHR_Civ_Random_OCimport_01 : LOP_CHR_Civ_Random { scope = 0; class EventHandlers; };
    class LOP_CHR_Civ_Random_OCimport_02 : LOP_CHR_Civ_Random_OCimport_01 { class EventHandlers; };

    class LOP_CHR_Civ_UAZ;
    class LOP_CHR_Civ_UAZ_OCimport_01 : LOP_CHR_Civ_UAZ { scope = 0; class EventHandlers; };
    class LOP_CHR_Civ_UAZ_OCimport_02 : LOP_CHR_Civ_UAZ_OCimport_01 { scope = 0; class EventHandlers; };

    class LOP_CHR_Civ_UAZ_Open;
    class LOP_CHR_Civ_UAZ_Open_OCimport_01 : LOP_CHR_Civ_UAZ_Open { scope = 0; class EventHandlers; class Turrets; };
    class LOP_CHR_Civ_UAZ_Open_OCimport_02 : LOP_CHR_Civ_UAZ_Open_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CargoTurret_01;
            class CargoTurret_02;
            class CargoTurret_03;
            class CargoTurret_04;
            class CargoTurret_05;
        };
    };

    class LOP_CHR_Civ_Ural;
    class LOP_CHR_Civ_Ural_OCimport_01 : LOP_CHR_Civ_Ural { scope = 0; class EventHandlers; class Turrets; };
    class LOP_CHR_Civ_Ural_OCimport_02 : LOP_CHR_Civ_Ural_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CargoTurret_01;
            class CargoTurret_02;
        };
    };

    class LOP_CHR_Civ_Ural_open;
    class LOP_CHR_Civ_Ural_open_OCimport_01 : LOP_CHR_Civ_Ural_open { scope = 0; class EventHandlers; class Turrets; };
    class LOP_CHR_Civ_Ural_open_OCimport_02 : LOP_CHR_Civ_Ural_open_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CargoTurret_01;
            class CargoTurret_02;
        };
    };

    class walker_a3_hatch;
    class walker_a3_hatch_OCimport_01 : walker_a3_hatch { scope = 0; class EventHandlers; };
    class walker_a3_hatch_OCimport_02 : walker_a3_hatch_OCimport_01 { scope = 0; class EventHandlers; };

    class walker_a3_gaz;
    class walker_a3_gaz_OCimport_01 : walker_a3_gaz { scope = 0; class EventHandlers; };
    class walker_a3_gaz_OCimport_02 : walker_a3_gaz_OCimport_01 { scope = 0; class EventHandlers; };

    class walker_a3_buscity;
    class walker_a3_buscity_OCimport_01 : walker_a3_buscity { scope = 0; class EventHandlers; };
    class walker_a3_buscity_OCimport_02 : walker_a3_buscity_OCimport_01 { scope = 0; class EventHandlers; };

    class walker_a3_hilux;
    class walker_a3_hilux_OCimport_01 : walker_a3_hilux { scope = 0; class EventHandlers; class Turrets; };
    class walker_a3_hilux_OCimport_02 : walker_a3_hilux_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CargoTurret_01;
            class CargoTurret_02;
        };
    };

    class walker_a3_c_hilux;
    class walker_a3_c_hilux_OCimport_01 : walker_a3_c_hilux { scope = 0; class EventHandlers; class Turrets; };
    class walker_a3_c_hilux_OCimport_02 : walker_a3_c_hilux_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CargoTurret_01;
            class CargoTurret_02;
        };
    };

    class RDS_JAWA353_Civ_01;
    class RDS_JAWA353_Civ_01_OCimport_01 : RDS_JAWA353_Civ_01 { scope = 0; class EventHandlers; class Turrets; };
    class RDS_JAWA353_Civ_01_OCimport_02 : RDS_JAWA353_Civ_01_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CargoTurret_01;
        };
    };

    class RDS_Gaz24_Civ_01;
    class RDS_Gaz24_Civ_01_OCimport_01 : RDS_Gaz24_Civ_01 { scope = 0; class EventHandlers; };
    class RDS_Gaz24_Civ_01_OCimport_02 : RDS_Gaz24_Civ_01_OCimport_01 { scope = 0; class EventHandlers; };

    class walker_a3_lada;
    class walker_a3_lada_OCimport_01 : walker_a3_lada { scope = 0; class EventHandlers; };
    class walker_a3_lada_OCimport_02 : walker_a3_lada_OCimport_01 { scope = 0; class EventHandlers; };

    class RDS_Old_bike_Civ_01;
    class RDS_Old_bike_Civ_01_OCimport_01 : RDS_Old_bike_Civ_01 { scope = 0; class EventHandlers; };
    class RDS_Old_bike_Civ_01_OCimport_02 : RDS_Old_bike_Civ_01_OCimport_01 { scope = 0; class EventHandlers; };

    class walker_a3_sedan;
    class walker_a3_sedan_OCimport_01 : walker_a3_sedan { scope = 0; class EventHandlers; };
    class walker_a3_sedan_OCimport_02 : walker_a3_sedan_OCimport_01 { scope = 0; class EventHandlers; };

    class walker_a3_s1203amb;
    class walker_a3_s1203amb_OCimport_01 : walker_a3_s1203amb { scope = 0; class EventHandlers; };
    class walker_a3_s1203amb_OCimport_02 : walker_a3_s1203amb_OCimport_01 { scope = 0; class EventHandlers; };

    class RDS_S1203_Civ_01;
    class RDS_S1203_Civ_01_OCimport_01 : RDS_S1203_Civ_01 { scope = 0; class EventHandlers; class Turrets; };
    class RDS_S1203_Civ_01_OCimport_02 : RDS_S1203_Civ_01_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CargoTurret_01;
            class CargoTurret_02;
        };
    };

    class walker_a3_s1203;
    class walker_a3_s1203_OCimport_01 : walker_a3_s1203 { scope = 0; class EventHandlers; };
    class walker_a3_s1203_OCimport_02 : walker_a3_s1203_OCimport_01 { scope = 0; class EventHandlers; };

    class walker_a3_skodovka;
    class walker_a3_skodovka_OCimport_01 : walker_a3_skodovka { scope = 0; class EventHandlers; };
    class walker_a3_skodovka_OCimport_02 : walker_a3_skodovka_OCimport_01 { scope = 0; class EventHandlers; };

    class RDS_Zetor6945_Base;
    class RDS_Zetor6945_Base_OCimport_01 : RDS_Zetor6945_Base { scope = 0; class EventHandlers; };
    class RDS_Zetor6945_Base_OCimport_02 : RDS_Zetor6945_Base_OCimport_01 { scope = 0; class EventHandlers; };

    class walker_a3_tractor_1;
    class walker_a3_tractor_1_OCimport_01 : walker_a3_tractor_1 { scope = 0; class EventHandlers; };
    class walker_a3_tractor_1_OCimport_02 : walker_a3_tractor_1_OCimport_01 { scope = 0; class EventHandlers; };


    class C_Cher90s_Civilian_01 : LOP_CHR_Civ_Villager_01_OCimport_02 {
        author = "carlmylo";
        scope = 2;
        scopeCurator = 2;
        displayName = "Civilian 1";
        side = 3;
        faction = "CIV_F_Cher90";

        identityTypes[] = {"Head_Euro","LanguageRUS","G_IRAN_default"};

        uniformClass = "LOP_U_CHR_Villager_01";

        linkedItems[] = {"LOP_H_Villager_cap"};
        respawnlinkedItems[] = {"LOP_H_Villager_cap"};

        weapons[] = {};
        respawnWeapons[] = {};

        magazines[] = {};
        respawnMagazines[] = {};

        ALiVE_orbatCreator_loadout[] = {{},{},{},{"LOP_U_CHR_Villager_01",{}},{},{},"LOP_H_Villager_cap","",{},{"","","","","",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class C_Cher90s_Civilian_02 : LOP_CHR_Civ_Villager_02_OCimport_02 {
        author = "carlmylo";
        scope = 2;
        scopeCurator = 2;
        displayName = "Civilian 2";
        side = 3;
        faction = "CIV_F_Cher90";

        identityTypes[] = {"Head_Euro","LanguageRUS","G_IRAN_default"};

        uniformClass = "LOP_U_CHR_Villager_02";

        linkedItems[] = {"LOP_H_Villager_cap"};
        respawnlinkedItems[] = {"LOP_H_Villager_cap"};

        weapons[] = {};
        respawnWeapons[] = {};

        magazines[] = {};
        respawnMagazines[] = {};

        ALiVE_orbatCreator_loadout[] = {{},{},{},{"LOP_U_CHR_Villager_02",{}},{},{},"LOP_H_Villager_cap","",{},{"","","","","",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class C_Cher90s_Civilian_03 : LOP_CHR_Civ_Villager_03_OCimport_02 {
        author = "carlmylo";
        scope = 2;
        scopeCurator = 2;
        displayName = "Civilian 3";
        side = 3;
        faction = "CIV_F_Cher90";

        identityTypes[] = {"Head_Euro","LanguageRUS","G_IRAN_default"};

        uniformClass = "LOP_U_CHR_Villager_03";

        linkedItems[] = {"LOP_H_Villager_cap"};
        respawnlinkedItems[] = {"LOP_H_Villager_cap"};

        weapons[] = {};
        respawnWeapons[] = {};

        magazines[] = {};
        respawnMagazines[] = {};

        ALiVE_orbatCreator_loadout[] = {{},{},{},{"LOP_U_CHR_Villager_03",{}},{},{},"LOP_H_Villager_cap","",{},{"","","","","",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class C_Cher90s_Civilian_04 : LOP_CHR_Civ_Villager_04_OCimport_02 {
        author = "carlmylo";
        scope = 2;
        scopeCurator = 2;
        displayName = "Civilian 4";
        side = 3;
        faction = "CIV_F_Cher90";

        identityTypes[] = {"Head_Euro","LanguageRUS","G_IRAN_default"};

        uniformClass = "LOP_U_CHR_Villager_04";

        linkedItems[] = {"LOP_H_Villager_cap"};
        respawnlinkedItems[] = {"LOP_H_Villager_cap"};

        weapons[] = {};
        respawnWeapons[] = {};

        magazines[] = {};
        respawnMagazines[] = {};

        ALiVE_orbatCreator_loadout[] = {{},{},{},{"LOP_U_CHR_Villager_04",{}},{},{},"LOP_H_Villager_cap","",{},{"","","","","",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class C_Cher90s_Civilian_05 : LOP_CHR_Civ_Woodlander_01_OCimport_02 {
        author = "carlmylo";
        scope = 2;
        scopeCurator = 2;
        displayName = "Civilian 5";
        side = 3;
        faction = "CIV_F_Cher90";

        identityTypes[] = {"Head_Euro","LanguageRUS","G_IRAN_default"};

        uniformClass = "LOP_U_CHR_Woodlander_01";

        linkedItems[] = {};
        respawnlinkedItems[] = {};

        weapons[] = {};
        respawnWeapons[] = {};

        magazines[] = {};
        respawnMagazines[] = {};

        ALiVE_orbatCreator_loadout[] = {{},{},{},{"LOP_U_CHR_Woodlander_01",{}},{},{},"","",{},{"","","","","",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class C_Cher90s_Civilian_06 : LOP_CHR_Civ_Woodlander_02_OCimport_02 {
        author = "carlmylo";
        scope = 2;
        scopeCurator = 2;
        displayName = "Civilian 6";
        side = 3;
        faction = "CIV_F_Cher90";

        identityTypes[] = {"Head_Euro","LanguageRUS","G_IRAN_default"};

        uniformClass = "LOP_U_CHR_Woodlander_02";

        linkedItems[] = {};
        respawnlinkedItems[] = {};

        weapons[] = {};
        respawnWeapons[] = {};

        magazines[] = {};
        respawnMagazines[] = {};

        ALiVE_orbatCreator_loadout[] = {{},{},{},{"LOP_U_CHR_Woodlander_02",{}},{},{},"","",{},{"","","","","",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class C_Cher90s_Civilian_07 : LOP_CHR_Civ_Woodlander_03_OCimport_02 {
        author = "carlmylo";
        scope = 2;
        scopeCurator = 2;
        displayName = "Civilian 7";
        side = 3;
        faction = "CIV_F_Cher90";

        identityTypes[] = {"Head_Euro","LanguageRUS","G_IRAN_default"};

        uniformClass = "LOP_U_CHR_Woodlander_03";

        linkedItems[] = {};
        respawnlinkedItems[] = {};

        weapons[] = {};
        respawnWeapons[] = {};

        magazines[] = {};
        respawnMagazines[] = {};

        ALiVE_orbatCreator_loadout[] = {{},{},{},{"LOP_U_CHR_Woodlander_03",{}},{},{},"","",{},{"","","","","",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class C_Cher90s_Civilian_08 : LOP_CHR_Civ_Woodlander_04_OCimport_02 {
        author = "carlmylo";
        scope = 2;
        scopeCurator = 2;
        displayName = "Civilian 8";
        side = 3;
        faction = "CIV_F_Cher90";

        identityTypes[] = {"Head_Euro","LanguageRUS","G_IRAN_default"};

        uniformClass = "LOP_U_CHR_Woodlander_04";

        linkedItems[] = {};
        respawnlinkedItems[] = {};

        weapons[] = {};
        respawnWeapons[] = {};

        magazines[] = {};
        respawnMagazines[] = {};

        ALiVE_orbatCreator_loadout[] = {{},{},{},{"LOP_U_CHR_Woodlander_04",{}},{},{},"","",{},{"","","","","",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class C_Cher90s_Civilian_09 : LOP_CHR_Civ_Worker_01_OCimport_02 {
        author = "carlmylo";
        scope = 2;
        scopeCurator = 2;
        displayName = "Civilian 9";
        side = 3;
        faction = "CIV_F_Cher90";

        identityTypes[] = {"Head_Euro","LanguageRUS","G_IRAN_default"};

        uniformClass = "LOP_U_CHR_Worker_01";

        linkedItems[] = {"LOP_H_Worker_cap"};
        respawnlinkedItems[] = {"LOP_H_Worker_cap"};

        weapons[] = {};
        respawnWeapons[] = {};

        magazines[] = {};
        respawnMagazines[] = {};

        ALiVE_orbatCreator_loadout[] = {{},{},{},{"LOP_U_CHR_Worker_01",{}},{},{},"LOP_H_Worker_cap","",{},{"","","","","",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class C_Cher90s_Civilian_10 : LOP_CHR_Civ_Worker_02_OCimport_02 {
        author = "carlmylo";
        scope = 2;
        scopeCurator = 2;
        displayName = "Civilian 10";
        side = 3;
        faction = "CIV_F_Cher90";

        identityTypes[] = {"Head_Euro","LanguageRUS","G_IRAN_default"};

        uniformClass = "LOP_U_CHR_Worker_02";

        linkedItems[] = {"LOP_H_Worker_cap"};
        respawnlinkedItems[] = {"LOP_H_Worker_cap"};

        weapons[] = {};
        respawnWeapons[] = {};

        magazines[] = {};
        respawnMagazines[] = {};

        ALiVE_orbatCreator_loadout[] = {{},{},{},{"LOP_U_CHR_Worker_02",{}},{},{},"LOP_H_Worker_cap","",{},{"","","","","",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class C_Cher90s_Civilian_11 : LOP_CHR_Civ_Worker_03_OCimport_02 {
        author = "carlmylo";
        scope = 2;
        scopeCurator = 2;
        displayName = "Civilian 11";
        side = 3;
        faction = "CIV_F_Cher90";

        identityTypes[] = {"Head_Euro","LanguageRUS","G_IRAN_default"};

        uniformClass = "LOP_U_CHR_Worker_03";

        linkedItems[] = {"LOP_H_Worker_cap"};
        respawnlinkedItems[] = {"LOP_H_Worker_cap"};

        weapons[] = {};
        respawnWeapons[] = {};

        magazines[] = {};
        respawnMagazines[] = {};

        ALiVE_orbatCreator_loadout[] = {{},{},{},{"LOP_U_CHR_Worker_03",{}},{},{},"LOP_H_Worker_cap","",{},{"","","","","",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class C_Cher90s_Civilian_12 : LOP_CHR_Civ_Worker_04_OCimport_02 {
        author = "carlmylo";
        scope = 2;
        scopeCurator = 2;
        displayName = "Civilian 12";
        side = 3;
        faction = "CIV_F_Cher90";

        identityTypes[] = {"Head_Euro","LanguageRUS","G_IRAN_default"};

        uniformClass = "LOP_U_CHR_Worker_04";

        linkedItems[] = {"LOP_H_Worker_cap"};
        respawnlinkedItems[] = {"LOP_H_Worker_cap"};

        weapons[] = {};
        respawnWeapons[] = {};

        magazines[] = {};
        respawnMagazines[] = {};

        ALiVE_orbatCreator_loadout[] = {{},{},{},{"LOP_U_CHR_Worker_04",{}},{},{},"LOP_H_Worker_cap","",{},{"","","","","",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class C_Cher90s_Civilian_13 : LOP_CHR_Civ_Rocker_01_OCimport_02 {
        author = "carlmylo";
        scope = 2;
        scopeCurator = 2;
        displayName = "Civilian 13";
        side = 3;
        faction = "CIV_F_Cher90";

        identityTypes[] = {"Head_Euro","LanguageRUS","G_IRAN_default"};

        uniformClass = "LOP_U_CHR_Rocker_01";

        linkedItems[] = {"ItemMap","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"ItemMap","ItemCompass","ItemWatch"};

        weapons[] = {};
        respawnWeapons[] = {};

        magazines[] = {};
        respawnMagazines[] = {};

        ALiVE_orbatCreator_loadout[] = {{},{},{},{"LOP_U_CHR_Rocker_01",{}},{},{},"","",{},{"ItemMap","","","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class C_Cher90s_Civilian_14 : LOP_CHR_Civ_Rocker_02_OCimport_02 {
        author = "carlmylo";
        scope = 2;
        scopeCurator = 2;
        displayName = "Civilian 14";
        side = 3;
        faction = "CIV_F_Cher90";

        identityTypes[] = {"Head_Euro","LanguageRUS","G_IRAN_default"};

        uniformClass = "LOP_U_CHR_Rocker_02";

        linkedItems[] = {"ItemMap","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"ItemMap","ItemCompass","ItemWatch"};

        weapons[] = {};
        respawnWeapons[] = {};

        magazines[] = {};
        respawnMagazines[] = {};

        ALiVE_orbatCreator_loadout[] = {{},{},{},{"LOP_U_CHR_Rocker_02",{}},{},{},"","",{},{"ItemMap","","","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class C_Cher90s_Civilian_15 : LOP_CHR_Civ_Rocker_03_OCimport_02 {
        author = "carlmylo";
        scope = 2;
        scopeCurator = 2;
        displayName = "Civilian 15";
        side = 3;
        faction = "CIV_F_Cher90";

        identityTypes[] = {"Head_Euro","LanguageRUS","G_IRAN_default"};

        uniformClass = "LOP_U_CHR_Rocker_03";

        linkedItems[] = {"ItemMap","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"ItemMap","ItemCompass","ItemWatch"};

        weapons[] = {};
        respawnWeapons[] = {};

        magazines[] = {};
        respawnMagazines[] = {};

        ALiVE_orbatCreator_loadout[] = {{},{},{},{"LOP_U_CHR_Rocker_03",{}},{},{},"","",{},{"ItemMap","","","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class C_Cher90s_Civilian_16 : LOP_CHR_Civ_Rocker_04_OCimport_02 {
        author = "carlmylo";
        scope = 2;
        scopeCurator = 2;
        displayName = "Civilian 16";
        side = 3;
        faction = "CIV_F_Cher90";

        identityTypes[] = {"Head_Euro","LanguageRUS","G_IRAN_default"};

        uniformClass = "LOP_U_CHR_Rocker_04";

        linkedItems[] = {"ItemMap","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"ItemMap","ItemCompass","ItemWatch"};

        weapons[] = {};
        respawnWeapons[] = {};

        magazines[] = {};
        respawnMagazines[] = {};

        ALiVE_orbatCreator_loadout[] = {{},{},{},{"LOP_U_CHR_Rocker_04",{}},{},{},"","",{},{"ItemMap","","","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class C_Cher90s_Civilian_17 : LOP_CHR_Civ_Profiteer_01_OCimport_02 {
        author = "carlmylo";
        scope = 2;
        scopeCurator = 2;
        displayName = "Civilian 17";
        side = 3;
        faction = "CIV_F_Cher90";

        identityTypes[] = {"Head_Euro","LanguageRUS","G_IRAN_default"};

        uniformClass = "LOP_U_CHR_Profiteer_01";

        linkedItems[] = {"ItemMap","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"ItemMap","ItemCompass","ItemWatch"};

        weapons[] = {};
        respawnWeapons[] = {};

        magazines[] = {};
        respawnMagazines[] = {};

        ALiVE_orbatCreator_loadout[] = {{},{},{},{"LOP_U_CHR_Profiteer_01",{}},{},{},"","",{},{"ItemMap","","","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class C_Cher90s_Civilian_18 : LOP_CHR_Civ_Profiteer_02_OCimport_02 {
        author = "carlmylo";
        scope = 2;
        scopeCurator = 2;
        displayName = "Civilian 18";
        side = 3;
        faction = "CIV_F_Cher90";

        identityTypes[] = {"Head_Euro","LanguageRUS","G_IRAN_default"};

        uniformClass = "LOP_U_CHR_Profiteer_02";

        linkedItems[] = {"ItemMap","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"ItemMap","ItemCompass","ItemWatch"};

        weapons[] = {};
        respawnWeapons[] = {};

        magazines[] = {};
        respawnMagazines[] = {};

        ALiVE_orbatCreator_loadout[] = {{},{},{},{"LOP_U_CHR_Profiteer_02",{}},{},{},"","",{},{"ItemMap","","","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class C_Cher90s_Civilian_19 : LOP_CHR_Civ_Profiteer_03_OCimport_02 {
        author = "carlmylo";
        scope = 2;
        scopeCurator = 2;
        displayName = "Civilian 19";
        side = 3;
        faction = "CIV_F_Cher90";

        identityTypes[] = {"Head_Euro","LanguageRUS","G_IRAN_default"};

        uniformClass = "LOP_U_CHR_Profiteer_03";

        linkedItems[] = {"ItemMap","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"ItemMap","ItemCompass","ItemWatch"};

        weapons[] = {};
        respawnWeapons[] = {};

        magazines[] = {};
        respawnMagazines[] = {};

        ALiVE_orbatCreator_loadout[] = {{},{},{},{"LOP_U_CHR_Profiteer_03",{}},{},{},"","",{},{"ItemMap","","","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class C_Cher90s_Civilian_20 : LOP_CHR_Civ_Profiteer_04_OCimport_02 {
        author = "carlmylo";
        scope = 2;
        scopeCurator = 2;
        displayName = "Civilian 20";
        side = 3;
        faction = "CIV_F_Cher90";

        identityTypes[] = {"Head_Euro","LanguageRUS","G_IRAN_default"};

        uniformClass = "LOP_U_CHR_Profiteer_04";

        linkedItems[] = {"ItemMap","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"ItemMap","ItemCompass","ItemWatch"};

        weapons[] = {};
        respawnWeapons[] = {};

        magazines[] = {};
        respawnMagazines[] = {};

        ALiVE_orbatCreator_loadout[] = {{},{},{},{"LOP_U_CHR_Profiteer_04",{}},{},{},"","",{},{"ItemMap","","","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class C_Cher90s_Civilian_21 : LOP_CHR_Civ_Priest_01_OCimport_02 {
        author = "carlmylo";
        scope = 2;
        scopeCurator = 2;
        displayName = "Civilian 21";
        side = 3;
        faction = "CIV_F_Cher90";

        identityTypes[] = {"Head_Euro","LanguageRUS","G_IRAN_default"};

        uniformClass = "LOP_U_CHR_Priest_01";

        linkedItems[] = {"ItemMap","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"ItemMap","ItemCompass","ItemWatch"};

        weapons[] = {};
        respawnWeapons[] = {};

        magazines[] = {};
        respawnMagazines[] = {};

        ALiVE_orbatCreator_loadout[] = {{},{},{},{"LOP_U_CHR_Priest_01",{}},{},{},"","",{},{"ItemMap","","","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class C_Cher90s_Civilian_22 : LOP_CHR_Civ_Doctor_01_OCimport_02 {
        author = "carlmylo";
        scope = 2;
        scopeCurator = 2;
        displayName = "Civilian 22";
        side = 3;
        faction = "CIV_F_Cher90";

        identityTypes[] = {"Head_Euro","LanguageRUS","G_IRAN_default"};

        uniformClass = "LOP_U_CHR_Doctor_01";

        linkedItems[] = {"ItemMap","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"ItemMap","ItemCompass","ItemWatch"};

        weapons[] = {};
        respawnWeapons[] = {};

        magazines[] = {};
        respawnMagazines[] = {};

        ALiVE_orbatCreator_loadout[] = {{},{},{},{"LOP_U_CHR_Doctor_01",{}},{},{},"","",{},{"ItemMap","","","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class C_Cher90s_Civilian_23 : LOP_CHR_Civ_SchoolTeacher_OCimport_02 {
        author = "carlmylo";
        scope = 2;
        scopeCurator = 2;
        displayName = "Civilian 23";
        side = 3;
        faction = "CIV_F_Cher90";

        identityTypes[] = {"Head_Euro","LanguageRUS","G_IRAN_default"};

        uniformClass = "LOP_U_CHR_SchoolTeacher_01";

        linkedItems[] = {"ItemMap","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"ItemMap","ItemCompass","ItemWatch"};

        weapons[] = {};
        respawnWeapons[] = {};

        magazines[] = {};
        respawnMagazines[] = {};

        ALiVE_orbatCreator_loadout[] = {{},{},{},{"LOP_U_CHR_SchoolTeacher_01",{}},{},{},"","",{},{"ItemMap","","","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class C_Cher90s_Civilian_24 : LOP_CHR_Civ_Assistant_OCimport_02 {
        author = "carlmylo";
        scope = 2;
        scopeCurator = 2;
        displayName = "Civilian 24";
        side = 3;
        faction = "CIV_F_Cher90";

        identityTypes[] = {"Head_Euro","LanguageRUS","G_IRAN_default"};

        uniformClass = "LOP_U_CHR_Assistant_01";

        linkedItems[] = {"ItemMap","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"ItemMap","ItemCompass","ItemWatch"};

        weapons[] = {};
        respawnWeapons[] = {};

        magazines[] = {};
        respawnMagazines[] = {};

        ALiVE_orbatCreator_loadout[] = {{},{},{},{"LOP_U_CHR_Assistant_01",{}},{},{},"","",{},{"ItemMap","","","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class C_Cher90s_Civilian_25 : LOP_CHR_Civ_Policeman_01_OCimport_02 {
        author = "carlmylo";
        scope = 2;
        scopeCurator = 2;
        displayName = "Civilian 25";
        side = 3;
        faction = "CIV_F_Cher90";

        identityTypes[] = {"Head_Euro","LanguageRUS","G_IRAN_default"};

        uniformClass = "LOP_U_CHR_Policeman_01";

        linkedItems[] = {"LOP_H_Policeman_cap","ItemMap","ItemCompass"};
        respawnlinkedItems[] = {"LOP_H_Policeman_cap","ItemMap","ItemCompass"};

        weapons[] = {"rhs_weap_makarov_pmm"};
        respawnWeapons[] = {"rhs_weap_makarov_pmm"};

        magazines[] = {"rhs_mag_9x18_12_57N181S","rhs_mag_9x18_12_57N181S"};
        respawnMagazines[] = {"rhs_mag_9x18_12_57N181S","rhs_mag_9x18_12_57N181S"};

        ALiVE_orbatCreator_loadout[] = {{},{},{"rhs_weap_makarov_pmm","","","",{"rhs_mag_9x18_12_57N181S",12},{},""},{"LOP_U_CHR_Policeman_01",{{"rhs_mag_9x18_12_57N181S",2,12}}},{},{},"LOP_H_Policeman_cap","",{},{"ItemMap","","","ItemCompass","",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class C_Cher90s_Civilian_26 : LOP_CHR_Civ_Functionary_01_OCimport_02 {
        author = "carlmylo";
        scope = 2;
        scopeCurator = 2;
        displayName = "Civilian 26";
        side = 3;
        faction = "CIV_F_Cher90";

        identityTypes[] = {"Head_Euro","LanguageRUS","G_IRAN_default"};

        uniformClass = "LOP_U_CHR_Functionary_01";

        linkedItems[] = {"ItemMap","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"ItemMap","ItemCompass","ItemWatch"};

        weapons[] = {};
        respawnWeapons[] = {};

        magazines[] = {};
        respawnMagazines[] = {};

        ALiVE_orbatCreator_loadout[] = {{},{},{},{"LOP_U_CHR_Functionary_01",{}},{},{},"","",{},{"ItemMap","","","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class C_Cher90s_Civilian_27 : LOP_CHR_Civ_Functionary_02_OCimport_02 {
        author = "carlmylo";
        scope = 2;
        scopeCurator = 2;
        displayName = "Civilian 27";
        side = 3;
        faction = "CIV_F_Cher90";

        identityTypes[] = {"Head_Euro","LanguageRUS","G_IRAN_default"};

        uniformClass = "LOP_U_CHR_Functionary_02";

        linkedItems[] = {"ItemMap","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"ItemMap","ItemCompass","ItemWatch"};

        weapons[] = {};
        respawnWeapons[] = {};

        magazines[] = {};
        respawnMagazines[] = {};

        ALiVE_orbatCreator_loadout[] = {{},{},{},{"LOP_U_CHR_Functionary_02",{}},{},{},"","",{},{"ItemMap","","","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class C_Cher90s_Civilian_28 : LOP_CHR_Civ_Citizen_01_OCimport_02 {
        author = "carlmylo";
        scope = 2;
        scopeCurator = 2;
        displayName = "Civilian 28";
        side = 3;
        faction = "CIV_F_Cher90";

        identityTypes[] = {"Head_Euro","LanguageRUS","G_IRAN_default"};

        uniformClass = "LOP_U_CHR_Citizen_01";

        linkedItems[] = {"LOP_H_Villager_cap"};
        respawnlinkedItems[] = {"LOP_H_Villager_cap"};

        weapons[] = {};
        respawnWeapons[] = {};

        magazines[] = {};
        respawnMagazines[] = {};

        ALiVE_orbatCreator_loadout[] = {{},{},{},{"LOP_U_CHR_Citizen_01",{}},{},{},"LOP_H_Villager_cap","",{},{"","","","","",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class C_Cher90s_Civilian_29 : LOP_CHR_Civ_Citizen_02_OCimport_02 {
        author = "carlmylo";
        scope = 2;
        scopeCurator = 2;
        displayName = "Civilian 29";
        side = 3;
        faction = "CIV_F_Cher90";

        identityTypes[] = {"Head_Euro","LanguageRUS","G_IRAN_default"};

        uniformClass = "LOP_U_CHR_Citizen_02";

        linkedItems[] = {"LOP_H_Villager_cap"};
        respawnlinkedItems[] = {"LOP_H_Villager_cap"};

        weapons[] = {};
        respawnWeapons[] = {};

        magazines[] = {};
        respawnMagazines[] = {};

        ALiVE_orbatCreator_loadout[] = {{},{},{},{"LOP_U_CHR_Citizen_02",{}},{},{},"LOP_H_Villager_cap","",{},{"","","","","",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class C_Cher90s_Civilian_30 : LOP_CHR_Civ_Citizen_03_OCimport_02 {
        author = "carlmylo";
        scope = 2;
        scopeCurator = 2;
        displayName = "Civilian 30";
        side = 3;
        faction = "CIV_F_Cher90";

        identityTypes[] = {"Head_Euro","LanguageRUS","G_IRAN_default"};

        uniformClass = "LOP_U_CHR_Citizen_03";

        linkedItems[] = {"LOP_H_Villager_cap"};
        respawnlinkedItems[] = {"LOP_H_Villager_cap"};

        weapons[] = {};
        respawnWeapons[] = {};

        magazines[] = {};
        respawnMagazines[] = {};

        ALiVE_orbatCreator_loadout[] = {{},{},{},{"LOP_U_CHR_Citizen_03",{}},{},{},"LOP_H_Villager_cap","",{},{"","","","","",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class C_Cher90s_Civilian_31 : LOP_CHR_Civ_Citizen_04_OCimport_02 {
        author = "carlmylo";
        scope = 2;
        scopeCurator = 2;
        displayName = "Civilian 31";
        side = 3;
        faction = "CIV_F_Cher90";

        identityTypes[] = {"Head_Euro","LanguageRUS","G_IRAN_default"};

        uniformClass = "LOP_U_CHR_Citizen_04";

        linkedItems[] = {"LOP_H_Villager_cap"};
        respawnlinkedItems[] = {"LOP_H_Villager_cap"};

        weapons[] = {};
        respawnWeapons[] = {};

        magazines[] = {};
        respawnMagazines[] = {};

        ALiVE_orbatCreator_loadout[] = {{},{},{},{"LOP_U_CHR_Citizen_04",{}},{},{},"LOP_H_Villager_cap","",{},{"","","","","",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class C_Cher90s_Civilian_32 : LOP_CHR_Civ_Random_OCimport_02 {
        author = "carlmylo";
        scope = 2;
        scopeCurator = 2;
        displayName = "Civilian 32";
        side = 3;
        faction = "CIV_F_Cher90";

        identityTypes[] = {"Head_Euro","LanguageRUS","G_IRAN_default"};

        uniformClass = "LOP_U_CHR_Worker_04";

        linkedItems[] = {"LOP_H_Villager_cap"};
        respawnlinkedItems[] = {"LOP_H_Villager_cap"};

        weapons[] = {};
        respawnWeapons[] = {};

        magazines[] = {};
        respawnMagazines[] = {};

        ALiVE_orbatCreator_loadout[] = {{},{},{},{"LOP_U_CHR_Worker_04",{}},{},{},"LOP_H_Villager_cap","",{},{"","","","","",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class C_Cher90s_Civ_UAZ3151 : LOP_CHR_Civ_UAZ_OCimport_02 {
        author = "carlmylo";
        scope = 2;
        scopeCurator = 2;
        displayName = "UAZ-3151";
        side = 3;
        faction = "CIV_F_Cher90";
        crew = "C_Cher90s_Civilian_19";


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class C_Cher90s_Civ_UAZ3151O : LOP_CHR_Civ_UAZ_Open_OCimport_02 {
        author = "carlmylo";
        scope = 2;
        scopeCurator = 2;
        displayName = "UAZ-3151 (Open)";
        side = 3;
        faction = "CIV_F_Cher90";
        crew = "C_Cher90s_Civilian_03";

        class Turrets : Turrets {
            class CargoTurret_01 : CargoTurret_01 { gunnerType = ""; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = ""; };
            class CargoTurret_03 : CargoTurret_03 { gunnerType = ""; };
            class CargoTurret_04 : CargoTurret_04 { gunnerType = ""; };
            class CargoTurret_05 : CargoTurret_05 { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class C_Cher90s_Civ_Ural : LOP_CHR_Civ_Ural_OCimport_02 {
        author = "carlmylo";
        scope = 2;
        scopeCurator = 2;
        displayName = "Ural-4320";
        side = 3;
        faction = "CIV_F_Cher90";
        crew = "LOP_CHR_Civ_Random";

        class Turrets : Turrets {
            class CargoTurret_01 : CargoTurret_01 { gunnerType = ""; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class C_Cher90s_Civ_UralOpen : LOP_CHR_Civ_Ural_open_OCimport_02 {
        author = "carlmylo";
        scope = 2;
        scopeCurator = 2;
        displayName = "Ural-4320 (Open)";
        side = 3;
        faction = "CIV_F_Cher90";
        crew = "C_Cher90s_Civilian_15";

        class Turrets : Turrets {
            class CargoTurret_01 : CargoTurret_01 { gunnerType = ""; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class C_Cher90s_Civ_Hatch : walker_a3_hatch_OCimport_02 {
        author = "carlmylo";
        scope = 2;
        scopeCurator = 2;
        displayName = "Hatch";
        side = 3;
        faction = "CIV_F_Cher90";
        crew = "C_Cher90s_Civilian_02";


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class C_Cher90s_Civ_GazB : walker_a3_gaz_OCimport_02 {
        author = "carlmylo";
        scope = 2;
        scopeCurator = 2;
        displayName = "GAZ 24 B";
        side = 3;
        faction = "CIV_F_Cher90";
        crew = "C_Cher90s_Civilian_25";


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class C_Cher90s_Civ_Bus : walker_a3_buscity_OCimport_02 {
        author = "carlmylo";
        scope = 2;
        scopeCurator = 2;
        displayName = "Bus";
        side = 3;
        faction = "CIV_F_Cher90";
        crew = "C_Cher90s_Civilian_01";


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class C_Cher90s_Civ_Hilux : walker_a3_hilux_OCimport_02 {
        author = "carlmylo";
        scope = 2;
        scopeCurator = 2;
        displayName = "Hilux";
        side = 3;
        faction = "CIV_F_Cher90";
        crew = "C_Cher90s_Civilian_27";

        class Turrets : Turrets {
            class CargoTurret_01 : CargoTurret_01 { gunnerType = ""; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class C_Cher90s_Civ_HiluxC : walker_a3_c_hilux_OCimport_02 {
        author = "carlmylo";
        scope = 2;
        scopeCurator = 2;
        displayName = "Hilux (Covered)";
        side = 3;
        faction = "CIV_F_Cher90";
        crew = "C_Cher90s_Civilian_24";

        class Turrets : Turrets {
            class CargoTurret_01 : CargoTurret_01 { gunnerType = ""; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class C_Cher90s_Civ_JAWA : RDS_JAWA353_Civ_01_OCimport_02 {
        author = "carlmylo";
        scope = 2;
        scopeCurator = 2;
        displayName = "Jawa";
        side = 3;
        faction = "CIV_F_Cher90";
        crew = "C_Cher90s_Civilian_12";

        class Turrets : Turrets {
            class CargoTurret_01 : CargoTurret_01 { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class C_Cher90s_Civ_Gaz : RDS_Gaz24_Civ_01_OCimport_02 {
        author = "carlmylo";
        scope = 2;
        scopeCurator = 2;
        displayName = "GAZ 24";
        side = 3;
        faction = "CIV_F_Cher90";
        crew = "C_Cher90s_Civilian_08";


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class C_Cher90s_Civ_Lada : walker_a3_lada_OCimport_02 {
        author = "carlmylo";
        scope = 2;
        scopeCurator = 2;
        displayName = "Lada";
        side = 3;
        faction = "CIV_F_Cher90";
        crew = "C_Cher90s_Civilian_25";


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class C_Cher90s_Civ_Bike : RDS_Old_bike_Civ_01_OCimport_02 {
        author = "carlmylo";
        scope = 2;
        scopeCurator = 2;
        displayName = "Old Bike";
        side = 3;
        faction = "CIV_F_Cher90";
        crew = "C_Cher90s_Civilian_03";


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class C_Cher90s_Civ_Toyota : walker_a3_sedan_OCimport_02 {
        author = "carlmylo";
        scope = 2;
        scopeCurator = 2;
        displayName = "Toyota";
        side = 3;
        faction = "CIV_F_Cher90";
        crew = "C_Cher90s_Civilian_09";


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class C_Cher90s_Civ_Amb : walker_a3_s1203amb_OCimport_02 {
        author = "carlmylo";
        scope = 2;
        scopeCurator = 2;
        displayName = "Ambulance";
        side = 3;
        faction = "CIV_F_Cher90";
        crew = "C_Cher90s_Civilian_22";


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class C_Cher90s_Civ_S1203 : RDS_S1203_Civ_01_OCimport_02 {
        author = "carlmylo";
        scope = 2;
        scopeCurator = 2;
        displayName = "1203 Orange";
        side = 3;
        faction = "CIV_F_Cher90";
        crew = "C_Cher90s_Civilian_15";

        class Turrets : Turrets {
            class CargoTurret_01 : CargoTurret_01 { gunnerType = ""; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class C_Cher90s_Civ_1203B : walker_a3_s1203_OCimport_02 {
        author = "carlmylo";
        scope = 2;
        scopeCurator = 2;
        displayName = "1203 Blue";
        side = 3;
        faction = "CIV_F_Cher90";
        crew = "C_Cher90s_Civilian_07";


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class C_Cher90s_Civ_Skodo : walker_a3_skodovka_OCimport_02 {
        author = "carlmylo";
        scope = 2;
        scopeCurator = 2;
        displayName = "Skodovka";
        side = 3;
        faction = "CIV_F_Cher90";
        crew = "C_Cher90s_Civilian_03";


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class C_Cher90s_Civ_Tractor1 : RDS_Zetor6945_Base_OCimport_02 {
        author = "carlmylo";
        scope = 2;
        scopeCurator = 2;
        displayName = "Tractor 1";
        side = 3;
        faction = "CIV_F_Cher90";
        crew = "C_Cher90s_Civilian_03";


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class C_Cher90s_Civ_Tractor2 : walker_a3_tractor_1_OCimport_02 {
        author = "carlmylo";
        scope = 2;
        scopeCurator = 2;
        displayName = "Tractor 2";
        side = 3;
        faction = "CIV_F_Cher90";
        crew = "C_Cher90s_Civilian_06";


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

};