//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 212.150430 on Stable branch
// Generated with ALiVE version 1.19.0.2301051
//////////////////////////////////////////////////////////////////////////////////

class CfgFactionClasses {
    class CIV_F_LINGOR {
        displayName = "Civilians (Lingor)";
        side = 3;
        flag = "\po_main\data\ui\markers\Flag_racs_CO.paa";
        icon = "\po_main\data\ui\markers\Flag_racs_CO.paa";
        priority = 0;
    };
};

class CfgGroups {
    class Civilian {

        class CIV_F_LINGOR {
            name = "Civilians (Lingor)";

            class Infantry {
                name = "Infantry";

            };

            class SpecOps {
                name = "Special Forces";

            };

            class Motorized {
                name = "Motorized Infantry";

            };

            class Motorized_MTP {
                name = "Motorized Infantry (MTP)";

            };

            class Support {
                name = "Support Infantry";

            };

            class Mechanized {
                name = "Mechanized Infantry";

            };

            class Armored {
                name = "Armor";

            };

            class Artillery {
                name = "Artillery";

            };

            class Naval {
                name = "Naval";

            };

            class Air {
                name = "Air";

            };


        };

    };
};


class CBA_Extended_EventHandlers_base;

class CfgVehicles {

    class LOP_AFR_Civ_Man_01;
    class LOP_AFR_Civ_Man_01_OCimport_01 : LOP_AFR_Civ_Man_01 { scope = 0; class EventHandlers; };
    class LOP_AFR_Civ_Man_01_OCimport_02 : LOP_AFR_Civ_Man_01_OCimport_01 { class EventHandlers; };

    class vn_c_bicycle_01;
    class vn_c_bicycle_01_OCimport_01 : vn_c_bicycle_01 { scope = 0; class EventHandlers; class Turrets; };
    class vn_c_bicycle_01_OCimport_02 : vn_c_bicycle_01_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CargoTurret_01;
        };
    };

    class walker_a3_buscity;
    class walker_a3_buscity_OCimport_01 : walker_a3_buscity { scope = 0; class EventHandlers; };
    class walker_a3_buscity_OCimport_02 : walker_a3_buscity_OCimport_01 { scope = 0; class EventHandlers; };

    class vn_c_car_01_01;
    class vn_c_car_01_01_OCimport_01 : vn_c_car_01_01 { scope = 0; class EventHandlers; class Turrets; };
    class vn_c_car_01_01_OCimport_02 : vn_c_car_01_01_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class codriver_ffv;
        };
    };

    class vn_c_car_03_01;
    class vn_c_car_03_01_OCimport_01 : vn_c_car_03_01 { scope = 0; class EventHandlers; class Turrets; };
    class vn_c_car_03_01_OCimport_02 : vn_c_car_03_01_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class codriver_ffv;
            class cargo2_ffv;
            class cargo3_ffv;
        };
    };

    class vn_c_car_02_01;
    class vn_c_car_02_01_OCimport_01 : vn_c_car_02_01 { scope = 0; class EventHandlers; class Turrets; };
    class vn_c_car_02_01_OCimport_02 : vn_c_car_02_01_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class codriver_ffv;
            class cargo2_ffv;
            class cargo3_ffv;
            class cargo4_ffv;
        };
    };

    class walker_a3_c_datsun;
    class walker_a3_c_datsun_OCimport_01 : walker_a3_c_datsun { scope = 0; class EventHandlers; class Turrets; };
    class walker_a3_c_datsun_OCimport_02 : walker_a3_c_datsun_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CargoTurret_01;
            class CargoTurret_02;
        };
    };

    class walker_a3_datsun;
    class walker_a3_datsun_OCimport_01 : walker_a3_datsun { scope = 0; class EventHandlers; class Turrets; };
    class walker_a3_datsun_OCimport_02 : walker_a3_datsun_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CargoTurret_01;
            class CargoTurret_02;
        };
    };

    class RDS_Gaz24_Civ_02;
    class RDS_Gaz24_Civ_02_OCimport_01 : RDS_Gaz24_Civ_02 { scope = 0; class EventHandlers; };
    class RDS_Gaz24_Civ_02_OCimport_02 : RDS_Gaz24_Civ_02_OCimport_01 { scope = 0; class EventHandlers; };

    class walker_a3_gaz;
    class walker_a3_gaz_OCimport_01 : walker_a3_gaz { scope = 0; class EventHandlers; };
    class walker_a3_gaz_OCimport_02 : walker_a3_gaz_OCimport_01 { scope = 0; class EventHandlers; };

    class walker_a3_hatch;
    class walker_a3_hatch_OCimport_01 : walker_a3_hatch { scope = 0; class EventHandlers; };
    class walker_a3_hatch_OCimport_02 : walker_a3_hatch_OCimport_01 { scope = 0; class EventHandlers; };

    class walker_a3_c_hilux;
    class walker_a3_c_hilux_OCimport_01 : walker_a3_c_hilux { scope = 0; class EventHandlers; class Turrets; };
    class walker_a3_c_hilux_OCimport_02 : walker_a3_c_hilux_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CargoTurret_01;
            class CargoTurret_02;
        };
    };

    class walker_a3_v_hilux;
    class walker_a3_v_hilux_OCimport_01 : walker_a3_v_hilux { scope = 0; class EventHandlers; class Turrets; };
    class walker_a3_v_hilux_OCimport_02 : walker_a3_v_hilux_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CargoTurret_01;
            class CargoTurret_02;
        };
    };

    class walker_a3_hilux;
    class walker_a3_hilux_OCimport_01 : walker_a3_hilux { scope = 0; class EventHandlers; class Turrets; };
    class walker_a3_hilux_OCimport_02 : walker_a3_hilux_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CargoTurret_01;
            class CargoTurret_02;
        };
    };

    class walker_a3_ikarusCIV;
    class walker_a3_ikarusCIV_OCimport_01 : walker_a3_ikarusCIV { scope = 0; class EventHandlers; };
    class walker_a3_ikarusCIV_OCimport_02 : walker_a3_ikarusCIV_OCimport_01 { scope = 0; class EventHandlers; };

    class RDS_Ikarus_Civ_01;
    class RDS_Ikarus_Civ_01_OCimport_01 : RDS_Ikarus_Civ_01 { scope = 0; class EventHandlers; };
    class RDS_Ikarus_Civ_01_OCimport_02 : RDS_Ikarus_Civ_01_OCimport_01 { scope = 0; class EventHandlers; };

    class RDS_JAWA353_Civ_01;
    class RDS_JAWA353_Civ_01_OCimport_01 : RDS_JAWA353_Civ_01 { scope = 0; class EventHandlers; class Turrets; };
    class RDS_JAWA353_Civ_01_OCimport_02 : RDS_JAWA353_Civ_01_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CargoTurret_01;
        };
    };

    class walker_a3_lada;
    class walker_a3_lada_OCimport_01 : walker_a3_lada { scope = 0; class EventHandlers; };
    class walker_a3_lada_OCimport_02 : walker_a3_lada_OCimport_01 { scope = 0; class EventHandlers; };

    class walker_a3_sedan;
    class walker_a3_sedan_OCimport_01 : walker_a3_sedan { scope = 0; class EventHandlers; };
    class walker_a3_sedan_OCimport_02 : walker_a3_sedan_OCimport_01 { scope = 0; class EventHandlers; };

    class RDS_S1203_Civ_01;
    class RDS_S1203_Civ_01_OCimport_01 : RDS_S1203_Civ_01 { scope = 0; class EventHandlers; class Turrets; };
    class RDS_S1203_Civ_01_OCimport_02 : RDS_S1203_Civ_01_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CargoTurret_01;
            class CargoTurret_02;
        };
    };

    class RDS_S1203_Civ_02;
    class RDS_S1203_Civ_02_OCimport_01 : RDS_S1203_Civ_02 { scope = 0; class EventHandlers; class Turrets; };
    class RDS_S1203_Civ_02_OCimport_02 : RDS_S1203_Civ_02_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CargoTurret_01;
            class CargoTurret_02;
        };
    };

    class walker_a3_skodovka;
    class walker_a3_skodovka_OCimport_01 : walker_a3_skodovka { scope = 0; class EventHandlers; };
    class walker_a3_skodovka_OCimport_02 : walker_a3_skodovka_OCimport_01 { scope = 0; class EventHandlers; };

    class walker_a3_tractor;
    class walker_a3_tractor_OCimport_01 : walker_a3_tractor { scope = 0; class EventHandlers; };
    class walker_a3_tractor_OCimport_02 : walker_a3_tractor_OCimport_01 { scope = 0; class EventHandlers; };

    class walker_a3_tractor_1;
    class walker_a3_tractor_1_OCimport_01 : walker_a3_tractor_1 { scope = 0; class EventHandlers; };
    class walker_a3_tractor_1_OCimport_02 : walker_a3_tractor_1_OCimport_01 { scope = 0; class EventHandlers; };

    class RDS_Lada_Civ_01;
    class RDS_Lada_Civ_01_OCimport_01 : RDS_Lada_Civ_01 { scope = 0; class EventHandlers; };
    class RDS_Lada_Civ_01_OCimport_02 : RDS_Lada_Civ_01_OCimport_01 { scope = 0; class EventHandlers; };

    class RDS_tt650_Civ_01;
    class RDS_tt650_Civ_01_OCimport_01 : RDS_tt650_Civ_01 { scope = 0; class EventHandlers; class Turrets; };
    class RDS_tt650_Civ_01_OCimport_02 : RDS_tt650_Civ_01_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CargoTurret_01;
        };
    };


    class C_Lingor_Civilian_01 : LOP_AFR_Civ_Man_01_OCimport_02 {
        author = "Carl Mylo";
        scope = 2;
        scopeCurator = 2;
        displayName = "Civilian 01";
        side = 3;
        faction = "civ_f_lingor";

        identityTypes[] = {"Head_Tanoan","LanguageFRE_F","G_CIVIL_male","NoGlasses"};

        uniformClass = "LOP_U_PMC_shorts_tan_olv";

        linkedItems[] = {"vn_b_item_watch"};
        respawnlinkedItems[] = {"vn_b_item_watch"};

        weapons[] = {};
        respawnWeapons[] = {};

        magazines[] = {};
        respawnMagazines[] = {};

        ALiVE_orbatCreator_loadout[] = {{},{},{},{"LOP_U_PMC_shorts_tan_olv",{}},{},{},"","",{},{"","","","","vn_b_item_watch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class C_Lingor_Civilian_02 : C_Lingor_Civilian_01 {
        author = "Carl Mylo";
        scope = 2;
        scopeCurator = 2;
        displayName = "Civilian 02";
        side = 3;
        faction = "civ_f_lingor";

        identityTypes[] = {"Head_Tanoan","LanguageFRE_F","G_CIVIL_male","NoGlasses"};

        uniformClass = "LOP_U_CHR_Citizen_04";

        linkedItems[] = {"vn_b_item_watch"};
        respawnlinkedItems[] = {"vn_b_item_watch"};

        weapons[] = {};
        respawnWeapons[] = {};

        magazines[] = {};
        respawnMagazines[] = {};

        ALiVE_orbatCreator_loadout[] = {{},{},{},{"LOP_U_CHR_Citizen_04",{}},{},{},"","",{},{"","","","","vn_b_item_watch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class C_Lingor_Civilian_03 : C_Lingor_Civilian_02 {
        author = "Carl Mylo";
        scope = 2;
        scopeCurator = 2;
        displayName = "Civilian 03";
        side = 3;
        faction = "civ_f_lingor";

        identityTypes[] = {"Head_Tanoan","LanguageFRE_F","G_CIVIL_male","NoGlasses"};

        uniformClass = "LOP_U_CHR_Villager_02";

        linkedItems[] = {"vn_b_item_watch"};
        respawnlinkedItems[] = {"vn_b_item_watch"};

        weapons[] = {};
        respawnWeapons[] = {};

        magazines[] = {};
        respawnMagazines[] = {};

        ALiVE_orbatCreator_loadout[] = {{},{},{},{"LOP_U_CHR_Villager_02",{}},{},{},"","",{},{"","","","","vn_b_item_watch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class C_Lingor_Civilian_04 : C_Lingor_Civilian_03 {
        author = "Carl Mylo";
        scope = 2;
        scopeCurator = 2;
        displayName = "Civilian 04";
        side = 3;
        faction = "civ_f_lingor";

        identityTypes[] = {"Head_Tanoan","LanguageFRE_F","G_CIVIL_male","NoGlasses"};

        uniformClass = "LOP_U_CHR_Rocker_04";

        linkedItems[] = {"vn_b_item_watch"};
        respawnlinkedItems[] = {"vn_b_item_watch"};

        weapons[] = {};
        respawnWeapons[] = {};

        magazines[] = {};
        respawnMagazines[] = {};

        ALiVE_orbatCreator_loadout[] = {{},{},{},{"LOP_U_CHR_Rocker_04",{}},{},{},"","",{},{"","","","","vn_b_item_watch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class C_Lingor_Civilian_05 : C_Lingor_Civilian_04 {
        author = "Carl Mylo";
        scope = 2;
        scopeCurator = 2;
        displayName = "Civilian 05";
        side = 3;
        faction = "civ_f_lingor";

        identityTypes[] = {"Head_Tanoan","LanguageFRE_F","G_CIVIL_male","NoGlasses"};

        uniformClass = "LOP_U_AFR_Civ_01S";

        linkedItems[] = {"vn_b_item_watch"};
        respawnlinkedItems[] = {"vn_b_item_watch"};

        weapons[] = {};
        respawnWeapons[] = {};

        magazines[] = {};
        respawnMagazines[] = {};

        ALiVE_orbatCreator_loadout[] = {{},{},{},{"LOP_U_AFR_Civ_01S",{}},{},{},"","",{},{"","","","","vn_b_item_watch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class C_Lingor_Civilian_06 : C_Lingor_Civilian_05 {
        author = "Carl Mylo";
        scope = 2;
        scopeCurator = 2;
        displayName = "Civilian 06";
        side = 3;
        faction = "civ_f_lingor";

        identityTypes[] = {"Head_Tanoan","LanguageFRE_F","G_CIVIL_male","NoGlasses"};

        uniformClass = "LOP_U_PMC_shorts_floral";

        linkedItems[] = {"vn_b_item_watch"};
        respawnlinkedItems[] = {"vn_b_item_watch"};

        weapons[] = {};
        respawnWeapons[] = {};

        magazines[] = {};
        respawnMagazines[] = {};

        ALiVE_orbatCreator_loadout[] = {{},{},{},{"LOP_U_PMC_shorts_floral",{}},{},{},"","",{},{"","","","","vn_b_item_watch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class C_Lingor_Civilian_07 : C_Lingor_Civilian_06 {
        author = "Carl Mylo";
        scope = 2;
        scopeCurator = 2;
        displayName = "Civilian 07";
        side = 3;
        faction = "civ_f_lingor";

        identityTypes[] = {"Head_Tanoan","LanguageFRE_F","G_CIVIL_male","NoGlasses"};

        uniformClass = "LOP_U_PMC_shorts_red_plaid";

        linkedItems[] = {"vn_b_item_watch"};
        respawnlinkedItems[] = {"vn_b_item_watch"};

        weapons[] = {};
        respawnWeapons[] = {};

        magazines[] = {};
        respawnMagazines[] = {};

        ALiVE_orbatCreator_loadout[] = {{},{},{},{"LOP_U_PMC_shorts_red_plaid",{}},{},{},"","",{},{"","","","","vn_b_item_watch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class C_Lingor_Civilian_08 : C_Lingor_Civilian_07 {
        author = "Carl Mylo";
        scope = 2;
        scopeCurator = 2;
        displayName = "Civilian 08";
        side = 3;
        faction = "civ_f_lingor";

        identityTypes[] = {"Head_Tanoan","LanguageFRE_F","G_CIVIL_male","NoGlasses"};

        uniformClass = "LOP_U_PMC_red_plaid";

        linkedItems[] = {"vn_b_item_watch"};
        respawnlinkedItems[] = {"vn_b_item_watch"};

        weapons[] = {};
        respawnWeapons[] = {};

        magazines[] = {};
        respawnMagazines[] = {};

        ALiVE_orbatCreator_loadout[] = {{},{},{},{"LOP_U_PMC_red_plaid",{}},{},{},"","",{},{"","","","","vn_b_item_watch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class C_Lingor_Civilian_09 : C_Lingor_Civilian_08 {
        author = "Carl Mylo";
        scope = 2;
        scopeCurator = 2;
        displayName = "Civilian 09";
        side = 3;
        faction = "civ_f_lingor";

        identityTypes[] = {"Head_Tanoan","LanguageFRE_F","G_CIVIL_male","NoGlasses"};

        uniformClass = "LOP_U_CHR_Worker_03";

        linkedItems[] = {"H_Construction_earprot_yellow_F","vn_b_item_watch"};
        respawnlinkedItems[] = {"H_Construction_earprot_yellow_F","vn_b_item_watch"};

        weapons[] = {};
        respawnWeapons[] = {};

        magazines[] = {};
        respawnMagazines[] = {};

        ALiVE_orbatCreator_loadout[] = {{},{},{},{"LOP_U_CHR_Worker_03",{}},{},{},"H_Construction_earprot_yellow_F","",{},{"","","","","vn_b_item_watch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class C_Lingor_Civilian_10 : C_Lingor_Civilian_09 {
        author = "Carl Mylo";
        scope = 2;
        scopeCurator = 2;
        displayName = "Civilian 10";
        side = 3;
        faction = "civ_f_lingor";

        identityTypes[] = {"Head_Tanoan","LanguageFRE_F","G_CIVIL_male","NoGlasses"};

        uniformClass = "LOP_U_AFR_Civ_03";

        linkedItems[] = {"LOP_H_Cowboy_hat","vn_b_item_watch"};
        respawnlinkedItems[] = {"LOP_H_Cowboy_hat","vn_b_item_watch"};

        weapons[] = {};
        respawnWeapons[] = {};

        magazines[] = {};
        respawnMagazines[] = {};

        ALiVE_orbatCreator_loadout[] = {{},{},{},{"LOP_U_AFR_Civ_03",{}},{},{},"LOP_H_Cowboy_hat","",{},{"","","","","vn_b_item_watch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class C_Lingor_Civilian_11 : C_Lingor_Civilian_10 {
        author = "Carl Mylo";
        scope = 2;
        scopeCurator = 2;
        displayName = "Civilian 11";
        side = 3;
        faction = "civ_f_lingor";

        identityTypes[] = {"Head_Tanoan","LanguageFRE_F","G_CIVIL_male","NoGlasses"};

        uniformClass = "LOP_U_CHR_Profiteer_04";

        linkedItems[] = {"rhs_beanie_green","vn_b_item_watch"};
        respawnlinkedItems[] = {"rhs_beanie_green","vn_b_item_watch"};

        weapons[] = {};
        respawnWeapons[] = {};

        magazines[] = {};
        respawnMagazines[] = {};

        ALiVE_orbatCreator_loadout[] = {{},{},{},{"LOP_U_CHR_Profiteer_04",{}},{},{},"rhs_beanie_green","",{},{"","","","","vn_b_item_watch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class C_Lingor_Civilian_Doctor : C_Lingor_Civilian_11 {
        author = "Carl Mylo";
        scope = 2;
        scopeCurator = 2;
        displayName = "Civilian Doctor";
        side = 3;
        faction = "civ_f_lingor";

        identityTypes[] = {"Head_Tanoan","LanguageFRE_F","G_CIVIL_male","NoGlasses"};

        uniformClass = "rds_uniform_doctor";

        linkedItems[] = {"vn_b_item_watch"};
        respawnlinkedItems[] = {"vn_b_item_watch"};

        weapons[] = {};
        respawnWeapons[] = {};

        magazines[] = {};
        respawnMagazines[] = {};

        ALiVE_orbatCreator_loadout[] = {{},{},{},{"rds_uniform_doctor",{}},{},{},"","",{},{"","","","","vn_b_item_watch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class C_Lingor_Bicycle_01 : vn_c_bicycle_01_OCimport_02 {
        author = "Carl Mylo";
        scope = 2;
        scopeCurator = 2;
        displayName = "Bicycle";
        side = 3;
        faction = "civ_f_lingor";
        crew = "C_Lingor_Civilian_01";

        class Turrets : Turrets {
            class CargoTurret_01 : CargoTurret_01 { gunnerType = "C_Lingor_Civilian_02"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class C_Lingor_Bus_City : walker_a3_buscity_OCimport_02 {
        author = "Carl Mylo";
        scope = 2;
        scopeCurator = 2;
        displayName = "Bus City";
        side = 3;
        faction = "civ_f_lingor";
        crew = "C_Lingor_Civilian_11";


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class C_Lingor_Car_Boheme_Bonn : vn_c_car_01_01_OCimport_02 {
        author = "Carl Mylo";
        scope = 2;
        scopeCurator = 2;
        displayName = "Car (Boheme Bonn)";
        side = 3;
        faction = "civ_f_lingor";
        crew = "C_Lingor_Civilian_02";

        class Turrets : Turrets {
            class codriver_ffv : codriver_ffv { gunnerType = "C_Lingor_Civilian_01"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class C_Lingor_Car_Boheme_Kupe : vn_c_car_03_01_OCimport_02 {
        author = "Carl Mylo";
        scope = 2;
        scopeCurator = 2;
        displayName = "Car (Boheme Kupe)";
        side = 3;
        faction = "civ_f_lingor";
        crew = "C_Lingor_Civilian_04";

        class Turrets : Turrets {
            class codriver_ffv : codriver_ffv { gunnerType = "C_Lingor_Civilian_07"; };
            class cargo2_ffv : cargo2_ffv { gunnerType = ""; };
            class cargo3_ffv : cargo3_ffv { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class C_Lingor_Car_Boheme_Rodina : vn_c_car_02_01_OCimport_02 {
        author = "Carl Mylo";
        scope = 2;
        scopeCurator = 2;
        displayName = "Car (Boheme Rodina)";
        side = 3;
        faction = "civ_f_lingor";
        crew = "C_Lingor_Civilian_08";

        class Turrets : Turrets {
            class codriver_ffv : codriver_ffv { gunnerType = "C_Lingor_Civilian_11"; };
            class cargo2_ffv : cargo2_ffv { gunnerType = ""; };
            class cargo3_ffv : cargo3_ffv { gunnerType = ""; };
            class cargo4_ffv : cargo4_ffv { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class C_Lingor_Datstun_Covered : walker_a3_c_datsun_OCimport_02 {
        author = "Carl Mylo";
        scope = 2;
        scopeCurator = 2;
        displayName = "Datstun Covered";
        side = 3;
        faction = "civ_f_lingor";
        crew = "C_Lingor_Civilian_09";

        class Turrets : Turrets {
            class CargoTurret_01 : CargoTurret_01 { gunnerType = ""; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class C_Lingor_Datsun_Open : walker_a3_datsun_OCimport_02 {
        author = "Carl Mylo";
        scope = 2;
        scopeCurator = 2;
        displayName = "Datsun Open";
        side = 3;
        faction = "civ_f_lingor";
        crew = "C_Lingor_Civilian_10";

        class Turrets : Turrets {
            class CargoTurret_01 : CargoTurret_01 { gunnerType = ""; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class C_Lingor_GAZ_24 : RDS_Gaz24_Civ_02_OCimport_02 {
        author = "Carl Mylo";
        scope = 2;
        scopeCurator = 2;
        displayName = "GAZ-24";
        side = 3;
        faction = "civ_f_lingor";
        crew = "C_Lingor_Civilian_02";


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class C_Lingor_GAZ_Limo : walker_a3_gaz_OCimport_02 {
        author = "Carl Mylo";
        scope = 2;
        scopeCurator = 2;
        displayName = "GAZ Limo";
        side = 3;
        faction = "civ_f_lingor";
        crew = "C_Lingor_Civilian_08";


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class C_Lingor_Hatchback_A2 : walker_a3_hatch_OCimport_02 {
        author = "Carl Mylo";
        scope = 2;
        scopeCurator = 2;
        displayName = "Hatchback A2";
        side = 3;
        faction = "civ_f_lingor";
        crew = "C_Lingor_Civilian_05";


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class C_Lingor_Hilux_Covered : walker_a3_c_hilux_OCimport_02 {
        author = "Carl Mylo";
        scope = 2;
        scopeCurator = 2;
        displayName = "Hilux Covered";
        side = 3;
        faction = "civ_f_lingor";
        crew = "C_Lingor_Civilian_06";

        class Turrets : Turrets {
            class CargoTurret_01 : CargoTurret_01 { gunnerType = ""; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class C_Lingor_Hilux_Coyota : walker_a3_v_hilux_OCimport_02 {
        author = "Carl Mylo";
        scope = 2;
        scopeCurator = 2;
        displayName = "Hilux Coyota";
        side = 3;
        faction = "civ_f_lingor";
        crew = "C_Lingor_Civilian_07";

        class Turrets : Turrets {
            class CargoTurret_01 : CargoTurret_01 { gunnerType = ""; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class C_Lingor_Hilux_Open : walker_a3_hilux_OCimport_02 {
        author = "Carl Mylo";
        scope = 2;
        scopeCurator = 2;
        displayName = "Hilux Open";
        side = 3;
        faction = "civ_f_lingor";
        crew = "C_Lingor_Civilian_03";

        class Turrets : Turrets {
            class CargoTurret_01 : CargoTurret_01 { gunnerType = ""; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class C_Lingor_Ikarus_2 : walker_a3_ikarusCIV_OCimport_02 {
        author = "Carl Mylo";
        scope = 2;
        scopeCurator = 2;
        displayName = "Ikarus 2";
        side = 3;
        faction = "civ_f_lingor";
        crew = "C_Lingor_Civilian_11";


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class C_Lingor_Ikarus_26003 : RDS_Ikarus_Civ_01_OCimport_02 {
        author = "Carl Mylo";
        scope = 2;
        scopeCurator = 2;
        displayName = "Ikarus 260.03";
        side = 3;
        faction = "civ_f_lingor";
        crew = "C_Lingor_Civilian_02";


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class C_Lingor_Jawa_353 : RDS_JAWA353_Civ_01_OCimport_02 {
        author = "Carl Mylo";
        scope = 2;
        scopeCurator = 2;
        displayName = "Jawa 353";
        side = 3;
        faction = "civ_f_lingor";
        crew = "C_Lingor_Civilian_04";

        class Turrets : Turrets {
            class CargoTurret_01 : CargoTurret_01 { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class C_Lingor_Lada_White : walker_a3_lada_OCimport_02 {
        author = "Carl Mylo";
        scope = 2;
        scopeCurator = 2;
        displayName = "Lada White";
        side = 3;
        faction = "civ_f_lingor";
        crew = "C_Lingor_Civilian_07";


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class C_Lingor_Sedan : walker_a3_sedan_OCimport_02 {
        author = "Carl Mylo";
        scope = 2;
        scopeCurator = 2;
        displayName = "Sedan";
        side = 3;
        faction = "civ_f_lingor";
        crew = "C_Lingor_Civilian_06";


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class C_Lingor_Skoda_1203 : RDS_S1203_Civ_01_OCimport_02 {
        author = "Carl Mylo";
        scope = 2;
        scopeCurator = 2;
        displayName = "Skoda 1203";
        side = 3;
        faction = "civ_f_lingor";
        crew = "C_Lingor_Civilian_01";

        class Turrets : Turrets {
            class CargoTurret_01 : CargoTurret_01 { gunnerType = ""; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class C_Lingor_Skoda_1203_Ambulance : RDS_S1203_Civ_02_OCimport_02 {
        author = "Carl Mylo";
        scope = 2;
        scopeCurator = 2;
        displayName = "Skoda 1203 (Ambulance)";
        side = 3;
        faction = "civ_f_lingor";
        crew = "C_Lingor_Civilian_Doctor";

        class Turrets : Turrets {
            class CargoTurret_01 : CargoTurret_01 { gunnerType = ""; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class C_Lingor_Skodovka : walker_a3_skodovka_OCimport_02 {
        author = "Carl Mylo";
        scope = 2;
        scopeCurator = 2;
        displayName = "Skodovka";
        side = 3;
        faction = "civ_f_lingor";
        crew = "C_Lingor_Civilian_05";


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class C_Lingor_Tractor_01 : walker_a3_tractor_OCimport_02 {
        author = "Carl Mylo";
        scope = 2;
        scopeCurator = 2;
        displayName = "Tractor 1";
        side = 3;
        faction = "civ_f_lingor";
        crew = "C_Lingor_Civilian_03";


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class C_Lingor_Tractor_02 : walker_a3_tractor_1_OCimport_02 {
        author = "Carl Mylo";
        scope = 2;
        scopeCurator = 2;
        displayName = "Tractor 2";
        side = 3;
        faction = "civ_f_lingor";
        crew = "C_Lingor_Civilian_10";


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class C_Lingor_VAZ_2103 : RDS_Lada_Civ_01_OCimport_02 {
        author = "Carl Mylo";
        scope = 2;
        scopeCurator = 2;
        displayName = "VAZ-2103";
        side = 3;
        faction = "civ_f_lingor";
        crew = "C_Lingor_Civilian_09";


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class C_Lingor_Yamaha_TT_650 : RDS_tt650_Civ_01_OCimport_02 {
        author = "Carl Mylo";
        scope = 2;
        scopeCurator = 2;
        displayName = "Yamaha TT-650";
        side = 3;
        faction = "civ_f_lingor";
        crew = "C_Lingor_Civilian_06";

        class Turrets : Turrets {
            class CargoTurret_01 : CargoTurret_01 { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

};